#!/bin/bash
# ------------------------------------------------------------------
# [Marco]   Environment script project 2
#           This script is for setting alias, functions
#           or any kind of tool that could make life easier
#           
# ------------------------------------------------------------------

source tools/misc.sh

PROJECT2_SEMAPHORES_HOME=$(pwd)


